language: php
php:
  - 5.4
  - 5.5
  - 5.6
env:
  - SYMFONY_VERSION=2.7.6
  - SYMFONY_VERSION=dev-master

script:
   - phpunit --version

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - script: phpunit --version
