easy_admin:
    site_name: 'Learn-In Admin'
    entities:
        Usuario:
            class: UserBundle\Entity\Usuario
            list:
                fields: ['nombreCompleto','username','cursos','email','enabled','lastLogin','roles']
        Cursos:
            class: AppBundle\Entity\Curso  
        Comentarios:
            class: AppBundle\Entity\Comment