easy_admin:
    site_name: 'Learn-In Admin'
    entities:
        Usuario:
            class: UserBundle\Entity\Usuario
        Cursos:
            class: CursoBundle\Entity\Curso  
        Comentarios:
            class: CursoBundle\Entity\Comment