easy_admin:
    site_name: 'Learn-In Admin'
    entities:
        Users:
            class: UserBundle\Entity\Usuario
            list:
                fields:
                    - id
                    - username
                    - email
                    - nombreCompleto
                    - cursos
            form:
                fields:
                    - username
                    - email
                    - plainPassword
                    - roles
                    - enabled
                    - cursos
        Cursos:
            class: AppBundle\Entity\Curso