#Aviso: la relación many to many todavía no se puede mostrar en el admin bundle
#referencia: https://github.com/javiereguiluz/EasyAdminBundle/issues/423
easy_admin:
    site_name: 'Learn-In Admin'
    entities:
        Usuario:
            class: UserBundle\Entity\Usuario
            list:
                fields: ['nombreCompleto','username','email','enabled','lastLogin','roles']
            new:
                fields: ['nombreCompleto','username','email','enabled','password','roles']
            edit:
                fields: ['nombreCompleto','username','email','enabled','lastLogin','password','expiresAt','locked','expired','roles']
        Cursos:
            class: CursoBundle\Entity\Curso 
            new:
               fields: ['nombreCurso','codigoCurso'] 
        Documentos:
            class: DocumentBundle\Entity\Documento

        Tutorias:
            class: TutoriaBundle\Entity\Tutoria

        Comentarios:
            class: ForumBundle\Entity\Comentario

