imports:
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin.yml }
    - { resource: fos_user.yml }
    - { resource: doctrine_extensions.yml }
    - { resource: lexik_translations.yml }
    - { resource: vich_uploader.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
   locale: es
   mailer_encryption: tls
framework:
    esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: v
        #assets_version_format: "%%s?v=%%s"
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']


    form_themes:
        # other form themes
        - 'VichUploaderBundle:Form:fields.html.twig'
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["FOSCommentBundle",TutoriaBundle]
    #node: /app/.heroku/node/bin
    #node: %kernel.root_dir%/../.heroku/node/bin
    node: ~
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
            apply_to: "\.less$"
        uglifycss:
            bin: %kernel.root_dir%/../app/Resources/node_modules/.bin/uglifycss

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    encryption: "%mailer_encryption%"
    spool:     { type: memory }

braincrafted_bootstrap:
    css_preprocessor: lessphp
    jquery_path: %kernel.root_dir%/../web/js/jquery-2.1.1.min.js


genemu_form:
    select2: ~

fos_comment:
    db_driver: orm
    class:
        model:
            comment: ForumBundle\Entity\Comentario
            thread: ForumBundle\Entity\Thread
            vote: ForumBundle\Entity\Vote

stof_doctrine_extensions:
    default_locale: es
    translation_fallback: true
    orm:
        default:
            sluggable: true
            loggable: true
knp_gaufrette:
    stream_wrapper: ~

    adapters:
        product_adapter:
            local:
                directory: %kernel.root_dir%/../web/docs
        foo:
            aws_s3:
                service_id: 'acme.aws_s3.client'
                bucket_name: 'plataformavirtual'
                options:
                    directory: 'parcialesyhdt'

    filesystems:
        archivos:
            adapter:    foo
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    #disable_csrf_role: ROLE_USER
    body_converter:
        enabled: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'html'], fallback_format: html, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }

nelmio_api_doc: ~

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
sensio_framework_extra:
    request: { converters: true }
    view:    { annotations: false }
    router:  { annotations: true }