forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

document:
    resource: "@DocumentBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

    

app:
    resource: "@CursoBundle/Controller/"
    type:     annotation

default:
    resource: "@UserBundle/Controller/"
    type:     annotation

easy_admin_bundle:
    #resource: "@EasyAdminBundle/Controller/"
    resource: "@CursoBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

