tutoria:
    resource: "@TutoriaBundle/Controller/"
    type:     annotation
    prefix:   /

forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

document:
    resource: "@DocumentBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@CursoBundle/Controller/"
    type:     annotation

default:
    resource: "@UserBundle/Controller/"
    type:     annotation

easy_admin_bundle:
    #resource: "@EasyAdminBundle/Controller/"
    resource: "@CursoBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /adminEntity

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /traducciones


