# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value
#    kernel.listener.atd.access_denied.class: UserBundle\Listener\AccessDeniedListener
imports:
    - { resource: amazon.php}

services:
    kernel.listener.accessDenied:
        class:  UserBundle\Listener\AccessDeniedListener
        arguments: ["@session","@router", "@request_stack"]
        tags:
             - { name: kernel.event_listener, event: kernel.exception, method: onAccessDeniedException }
    acme.s3_client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
                version: 'lastest' # or 'latest'
                region: "eu-central-1'" # 'eu-central-1' for example
                credentials:
                    key: "%key%"
                    secret: "%secret%"