vich_uploader:
    db_driver: orm
    mappings:
        document:
            uri_prefix:         /docs
            upload_destination: %kernel.root_dir%/../web/docs
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
