UserBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: UserBundle\Entity\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombreCompleto:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
